# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_scripts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
