# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 20:51
from __future__ import unicode_literals

from django.db import migrations


def unhtmlize_scripts(apps, schema_editor):
    import html2text
    import json
    scripts = apps.get_model("scripts", "Script")
    for script in scripts.objects.all():
        script_data = json.loads(script.text)
        for scope in ("phrases", "replies"):
            for k, v in script_data[scope].items():
                script_data[scope][k]["text"] = html2text.html2text(v["text"])
        script.text = json.dumps(script_data)
        script.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20151229_1910'),
    ]

    operations = [
        migrations.RunPython(unhtmlize_scripts),
    ]
