# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '__latest__'),
        ('scripts', '0003_auto_20160312_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ('-created',), 'permissions': (('script_own', 'Script owner (r,w,x)'), ('script_execute', 'Run script in viewer with stats'), ('script_change', 'Save script in editor'), ('script_view', 'Run script in viewer w/o stats'))},
        ),
        migrations.AddField(
            model_name='scriptpermission',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='scripts.Script'),
        ),
        migrations.AddField(
            model_name='scriptpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='scriptpermission',
            unique_together=set([('script', 'user', 'permission')]),
        ),
    ]
